### ISSUE TITLE
Suggestions for image SEO

### ISSUE THREAD

**Issue by derivadow** [wellcometrust/wellcomecollection.org#1224]
## Type
- 🚑 Health report

## Needs

- [ ] Analytics and/or component tracking

## Acceptance Criteria

- [ ] sitemap should validate
- [ ] schema.org should validate
- [ ] Monitor performance in webmaster tools

## Problem to be solved / User Story
In order to help users discover images via Google (and other search engines) we need to ensure timely and accurate indexing by search engines.

## Suggested things to do:
~- [ ] Set-up and register an image sitemap (https://support.google.com/webmasters/answer/178636?hl=en)~ - covered by #1574
~- [ ] Alt text for images (?use image title or description)~ - covered by #1576

~- [ ] Create 'collection pages' to group images into semantically meaningful sets~ - covered by #1578

~- [x] Ensure Canonical URLs (either via rel="canonical" or one URL per work)~ - added in #1223

~- [ ] Provide HTML snippet for others to embed in their page (include links back + licensee)~ - added in #1579

~- [x] Download links for images of different sizes~ - added in #1338

~- [ ] Include mark-up thumbnail image~ - covered by #1580
~- [ ] include relevant schema.org tags~ - covered by #1581

**Comment by jennpb** [comment]
For discussion with team @jamesgorrie @gestchild @davidpmccormick @pollecuttn :
- What happens at work level vs. image level, given we'll have multi-image works in future.
- Sort out what schema.org tags are most relevant
- What changes need to happen now with single images from MIRO vs. all other content coming in in future? 

@derivadow It'd be good to have you in on this discussion. What do you mean by creating collection pages? This feels like a feature request rather than an SEO check at this stage.

**Comment by gestchild** [comment]
I'm closing this issue. 

A couple of the tasks in it have already been done and I've split the rest into more discrete issues, where we can capture more specific requirements, and prioritise accordingly.

All related issues are referenced above.
