### ISSUE TITLE
Item page: populating with workType from API

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1232]
- ✨ Feature

## Data requirements
As specified in #1004 

## Acceptance criteria
Can display:
- Genre

**Comment by pollecuttn** [comment]
From @ChristopherHilton "Genre" is a bit of a baggy one which I've been trying to make more precise, with three basic concepts in the ontology:
1/ WorkType - very broad top-level description of what sort of "thing" is this - book, picture, film, etc. We can do this from fields in Sierra and CALM; and everything coming out of MIRO, of course, is an image. (If it's an image of something else in the Library and we want to describe what that thing is, the details will be possible to pick up from the Sierra or CALM descriptions if we want to do that.)
2/ Genre - a description of the content - eg Obituary, Caricature, Non-Fiction
3/ Format - a description of the "thing" (not its content) in ways that are a bit more precise than WorkType and relate to precisely how that content is delivered - eg VHS video, etc.
Should be OK to do 1/ without too much bother. Where we got to at the end of Wednesday's modelling session was a realisation that the data as it currently stands may not make it easy to separate 2/ and 3/ - the same fields can mix together information about the content or the carrier medium, annoyingly. So tomorrow we'll be looking at whether it's possible to peel those apart or whether they have to be crunched together as one thing.
Hope that's helpful - which of these is the sort of thing you had in mind when putting Genre on the requirements?

**Comment by pollecuttn** [comment]
Genre from the API was originally on #1114

**Comment by pollecuttn** [comment]
@ChristopherHilton Please update this ticket for genre. It doesn't sound like worktype / genre / format will be represented as described above because thinking has moved on a bit.

**Comment by pollecuttn** [comment]
Depends on https://github.com/wellcometrust/platform-api/issues/618

**Comment by pollecuttn** [comment]
In the API, genre will have genre and technique (2 above) only. The data is primarily from Sierra from the Library of Congress [Thesaurus for Graphic Materials](http://www.loc.gov/pictures/collection/tgm/)

**Comment by pollecuttn** [comment]
@jennpb I've just removed the blocked label on this genre issue as genre is now coming through the API and is usable by the Experience team.
see https://api.wellcomecollection.org/catalogue/v0/works

It's not yet showing up on item pages:
https://next.wellcomecollection.org/works/a22au6yn

**Comment by jennpb** [comment]
@pollecuttn Thanks for letting us know. It will need to be added separately when time is right.

**Comment by ChristopherHilton** [comment]
Summarising where we are on this, moving information from Slack so that it's here on the ticket:
1/ Genre/Technique: the data we're working with don't for the most part seem to support the idea of separating content (eg satire, obituary) from physical format (watercolours, etchings), the same fields tend to get used for both those concepts.  So "Genre" is going to come out as a bit of a mix of concepts.
2/ WorkType: we will also be serving up a really basic top-level thing called "WorkType" which will be much broader than the sort of things that come through in Genre, and will just say "This is a book", "This is a picture" and things of that nature.
Some of what it was envisaged to deliver using "Genre" in earlier discussions may actually be better envisaged as coming through WorkType.

**Comment by jennpb** [comment]
#platform dependency: https://github.com/wellcometrust/platform/issues/787

**Comment by jennpb** [comment]
This is now in the v2 API and we will pick it up when we migrate the site to v2.
