### ISSUE TITLE
Build title lockup

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#126]
- [x] Article title
- [x] Publication date
- [x] Series label
- [x] Grey indent block

**Comment by davidpmccormick** [comment]
See https://cardigan.wellcomecollection.org/components/detail/page-description--default.html for the first three points.

The grey indent block is a standalone element that can live alongside any row of content, rather than just a title. It isn't displayed on its own in Cardigan, but it can be seen implemented e.g. on an article template https://cardigan.wellcomecollection.org/components/detail/article-template.html
