### ISSUE TITLE
Digitised content UX: design sprint process

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1307]
@jennpb to set the direction and overall plan for a design sprint at the end of Q4 

- [x] Confirm dates
- [ ] Invite externals
- [x] Find dedicated space for team work and testing on set date

**Comment by jennpb** [comment]
Based on method set out in _Sprint: how to solve big problems and test new ideas in just five days by Jake Knapp_. http://www.thesprintbook.com/tools/

**Purpose of sprint**
Build confidence that we’re building the right thing by testing ideas quickly
Decide what the surface does, then work backward to figure out underlying systems or technology

**Challenge**
To work out our approach the presentation and functionality of digitised content so that it will be most useful to our research audiences

- Read digital surrogate? Read on screen?
- Downloads
- Use of text and related data (statistics, images, OCR, index, table of contents)
- Zoom
- Compare editions
- Embed

**Sprint structure**
Day 1: Make a map and choose a target
Day 2: Sketch competing solutions
Day 3: Decide on the best options
Day 4: Build one (or more) realistic prototype(s)
Day 5: Test with target users

**Comment by jennpb** [comment]
Relates to #1305 and #1306

**Comment by hthair** [comment]
closing for now, will come back to in Q2.
