### ISSUE TITLE
Prioritise design work for September 2017

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1435]
@jennpb and @Heesoomoon to discuss ux / design priorities

**Comment by jennpb** [comment]
List of things currently on the radar:

- Picking up any accessibility recommendations, including colour contrast issues
- Picking up any recommendations for alignment with brand principles
- Handling image credits across the experience #772 
- Favicon/avatar #529 
- Logic of wobbly line # 801
- Standalone image gallery #1369 
- Use of whitespace and padding

**Comment by Heesoomoon** [comment]
The design tasks are tracked on Trello board.
https://trello.com/b/rjRu3w7V/design-work-sept-2017

**Comment by pollecuttn** [comment]
I don't have access to this board. Is it private? Can you please invite me an anyone else who needs to see it? Thanks!

**Comment by Heesoomoon** [comment]
@pollecuttn It looks like Jenn has given you the access already. Let me know if you want me to walk you through the board.

**Comment by Heesoomoon** [comment]
@jennpb I updated the board based on our conversation today. When Tomi comes in on Tuesday, I can walk through and have him estimate each task.

**Comment by jennpb** [comment]
@Heesoomoon Rather than spend time on estimating the whole list, could we just focus on those things that are currently in progress, like 
- things relating to image galleries, 
- anything that can help us enhance works pages (like clarifying type hierarchy and where/when to use lettera vs. helvetica)?

I think it'll be hard to estimate effort without seeing the problems in context and working with the team to iterate and implement.

**Comment by Heesoomoon** [comment]
If that’s the case, I’ll focus on Image Gallery and Exhibition page today with Tomi and address following tasks.

-          Review the grid and layout

-          Type hierarchy

-          Tag treatment

-          Colour scheme

Kind regards,
Heesoo

**Comment by Heesoomoon** [comment]
The latest prioritised list is posted.
https://trello.com/b/rjRu3w7V/design-work-sept-2017
