### ISSUE TITLE
Design: Update icons to improve usability and address alignment issues

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1545]
## Type
enhancement

## Detail
Update download and share icons based on user feedback
Provide a spec for use of icon with label
Recut the icon svg files to make it consistent size

**Comment by Norvard** [comment]
Final improved set of icons attached. This covers the main stylistic set associated with the site but does not cover every single icon we currently have (covers most however). There are still a few edge cases where icons are used that fall outside of this set, that is mainly due to their size within the page design. The set attached is based on a unified size and style. 

This clean up was done in order to ensure that these icons are utilised in a consistent way across the site. 
**The icons contained here should always be used in their 100% and only that size. Never reduce their size or grow it. This way the icons across the site are a consistent language that the user can learn and use**
They can however be used in any colour that the design calls for.

![screen shot 2017-09-20 at 11 11 55](https://user-images.githubusercontent.com/23660297/30638842-b6481d4a-9df4-11e7-8122-6ecd57f3c671.png)


Working AI file: 
[WC_Icons_2017.ai.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1317391/WC_Icons_2017.ai.zip)

Expanded AI file:
[WC_Icons_2017_Exp.ai.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1317390/WC_Icons_2017_Exp.ai.zip)

Exported SVGs:
[Icons_2.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1317389/Icons_2.zip)

**Comment by Heesoomoon** [comment]
Would you also put together few examples of links/buttons where we display icon and text label? e.g. Sort, Save, Download, etc.

**Comment by Norvard** [comment]
Some basic guidelines for icon use:
![screen shot 2017-09-20 at 12 08 35](https://user-images.githubusercontent.com/23660297/30640825-791f7190-9dfc-11e7-87d6-5c13ebe8408a.png)

**Comment by Norvard** [comment]
**Updated files:**

Working AI file:
[WC_Icons_2017.ai.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1332579/WC_Icons_2017.ai.zip)

Expanded AI file:
[WC_Icons_2017_Exp.ai.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1332581/WC_Icons_2017_Exp.ai.zip)

Exported SVGs:
[Icons_2.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1332575/Icons_2.zip)

**Comment by Norvard** [comment]
Once new icons get created. I will continue to add them to this thread.

**Comment by Norvard** [comment]
Added 3 CC icons:
@davidpmccormick 

SVGs:
[00_New 01.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1341406/00_New.01.zip)

Updated design files:
[Archive.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1341410/Archive.zip)

**Comment by Norvard** [comment]
Added 2 new icons:
@davidpmccormick 

SVGs:
[00_New 02.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1341545/00_New.02.zip)

Design files:
[Archive.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1341548/Archive.zip)

**Comment by Norvard** [comment]
Four new icons added
Rotate left, rotate right, rotate 360, add to clipboard 

SVGs:
[00_New 03.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1513679/00_New.03.zip)

AI:
[WC_Icons_2017_02.ai.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1513677/WC_Icons_2017_02.ai.zip)

**Comment by Norvard** [comment]
New AD icon:
[WC_AD_icon.ai.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1526586/WC_AD_icon.ai.zip)

[WC_Icons__AD.svg.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1526588/WC_Icons__AD.svg.zip)

![screen shot 2017-12-04 at 10 14 37](https://user-images.githubusercontent.com/23660297/33547466-0d1c4624-d8dc-11e7-87ed-8c2377477f23.png)

**Comment by Norvard** [comment]
Collection of icon SVGs that should be uploaded to Cardigan
@jamesgorrie 
[00_Upload SVGs.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1538679/00_Upload.SVGs.zip)

**Comment by Norvard** [comment]
Latest icon update. Can someone just upload the SVGs to cardigan so we have them in the future @davidpmccormick @jamesgorrie @gestchild  Few might be there already.

![screen shot 2017-12-19 at 14 17 28](https://user-images.githubusercontent.com/23660297/34161283-1f6ec200-e4c8-11e7-8409-145323f465db.png)

SVGs:
[00_New 04.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1571933/00_New.04.zip)


Working AI file:
[Uploading WC_Icons_2017_02.ai.zip…]()
