### ISSUE TITLE
Images: moire effect in IE11

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1557]
## Type
- 🐛 Bug

William S reported that some of the images are showing a moire/trippy wavy effect, particularly engravings, because of the nature of how they're created. It looks like this is a browser issue, given the difference between his browser (IE11) and Chrome and Safari. Suspect issue with client-side image scaling.

https://wellcomecollection.org/works/dpcvcghv?query=saint+Jerome+by+Masson
![20-09-2017 17-07-51](https://user-images.githubusercontent.com/1446139/30654792-ee4ae20e-9e26-11e7-9b2e-c098a0bb3361.png)

Here's another: https://wellcomecollection.org/works/yy4qnq7d?query=engraving

**Comment by davidpmccormick** [comment]
IEs 8–11 don't scale images down well (since the `-ms-interpolation-mode` property was dropped). 

An issue with our responsive image strategy here is that we're telling the browser that the images are 100% wide – this is true, but _only_ if they take up less than 80% of the viewport vertically, i.e. if they are landscape images.

Subsequently, we end up sending too-wide portrait images and IE suffers.

There isn't a native way for the browser's responsive images implementation to handle our as-wide-as-you-can-go-but-not-more-than-80%-high requirement. One 'solution' would be to measure the rendered image size with JS and then fetch the appropriate IIIF crop – [this feels like a bit of a dark path to go down](https://codepen.io/davidpmccormick/pen/WZGqdW?editors=0010).

**Comment by pollecuttn** [comment]
@davidpmccormick Has William (who reported this issue) been told it's not an issue now? Would you like me to as I'm on the email thread about it?

Also, does this need to be closed with an explanation that it's not fixed but why it's no longer an issue for us?

**Comment by davidpmccormick** [comment]
He hasn't, no – please let him know, yes!

I think it probably should be closed now, yep – nominate @gestchild to give the explanation.

**Comment by pollecuttn** [comment]
Done!

**Comment by gestchild** [comment]
As David noted above: 

> An issue with our responsive image strategy here is that we're telling the browser that the images are 100% wide – this is true, but only if they take up less than 80% of the viewport vertically, i.e. if they are landscape images.

> Subsequently, we end up sending too-wide portrait images and IE suffers.

Not only does IE suffer, in that it doesn't scale the images well, everyone is downloading images which are much larger than necessary, making the page weight much larger than it needs to be.

Now that users have the ability to zoom images, we have opted to restrict the size of the initial image on the page, which both dramatically reduces page weight and makes the IE scaling problem a non issue.
