### ISSUE TITLE
Search improvement: search creator as a phrase

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1932]
## Type
- ✨ Feature

## Problem to be solved
When on an individual /work page, the linked entities that form part of the description *should* allow the user to search for that phrase/entity specifically.

For example, I select a result from this search: https://wellcomecollection.org/works/ydudd428?query=Odra+Noel

And then pivot on Odra Noel as creator (https://wellcomecollection.org/works?query=creators%3AOdra%20Noel), and I would expect my search results to be refined to ONLY those work by Creator=Odra Noel.

Instead, I see the same set of results from the initial search, i.e. those results with Odra OR Noel in the query string. 

In the future we will have IDs which allow us to disambiguate this Odra Noel from Odra J Noel (for example), but for now, the only way to refine this is to wrap it in quotes around the creator string, e.g. `https://wellcomecollection.org/works?query=creators%3A%22Odra%20Noel%22`

**Comment by pollecuttn** [comment]
If we do start doing phrase searching the search results page needs to be amended to reflect this. It wrongly looks like the current OR search is a phrase search because the OR'd search terms are shown wrapped in quotes: 

> 165 results for "Odra Noel"

(Source: https://wellcomecollection.org/works?query=Odra+Noel)

We should keep search terms wrapped in quotes for phrase searching, and represent OR searching in another way.

**Comment by jamesgorrie** [comment]
@pollecuttn Yip - and when we specify the field i.e. creator:"Odra Noel".
There's a fix in for it.
