### ISSUE TITLE
Finishing off redirection of permanent exhibitions

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2002]
## Type
:sparkles: Feature

We need to redirect v1 Med Man and Med Now to v2

`https://wellcomecollection.org/exhibitions/medicine-now` to `https://wellcomecollection.org/exhibitions/WeobUyQAAKdwjbEO`

`https://wellcomecollection.org/exhibitions/medicine-man` to `https://wellcomecollection.org/exhibitions/Weoe4SQAAKJwjcDC`

BUT before we do that, we need to decide what to do about the three promos featured on v1:
- Promo for Curiosities from the Collection
- Promo for Image Gallery
- Promo for Young Explorers 

Options:

1. Take no action until we decide how to treat image galleries and related content in Jan/Feb
2. Create image gallery static images like we did with temporary exhibitions, to link to Drupal galleries; hardcode other two promos

Anything we can learn about CTR from v1 exhibition page to related content from GA, @hthair?

**Comment by jamesgorrie** [comment]
__For the year__

| | | | | | | |
|---|---|---|---|---|---|---|
|wellcomecollection.org/selection-objects-0 | 5,777(55.53%) | 5,445(55.53%) | 00:01:51 | 188(22.09%) | 70.00% | 32.53% |  
|wellcomecollection.org/selection-objects | 3,426(32.93%) | 3,256(33.21%) | 00:01:50 | 118(13.87%) | 51.24% | 33.22% |
| wellcomecollection.org/visit-us/curiosities-month | 8,319(93.51%) | 7,581(93.49%) | 00:02:12 | 484(57.48%) | 76.53% | 37.24% |
| wellcomecollection.org/visit-us/young-explorer-pack | 1,542(99.87%) | 1,391(99.86%) | 00:01:20 | 469(99.79%) | 56.05% | 43.64% |

On average-ish - it seems like < 20% of those are from internal traffic - so not unsubstantial, but not a lot.

Given the low amount of traffic, I would vote option 1, also to get the juice from the old pages as we now have both in SERPs.

![screen shot 2018-01-09 at 14 00 23](https://user-images.githubusercontent.com/31692/34724370-831d46fe-f545-11e7-89c8-197ac3abfd89.png)

**Comment by hthair** [comment]
selection-objects-0 Click throughs top previous page list:
![screen shot 2018-01-23 at 16 01 30](https://user-images.githubusercontent.com/26549021/35286028-c276e1d6-0056-11e8-89a5-05e9314ae475.png)

selection-objects previous page paths:
![screen shot 2018-01-23 at 16 02 40](https://user-images.githubusercontent.com/26549021/35286070-e01a76f8-0056-11e8-958f-1193c4e7445b.png)

curiosities-month:
![screen shot 2018-01-23 at 16 03 40](https://user-images.githubusercontent.com/26549021/35286127-09a1afc8-0057-11e8-82ad-c634cdabd310.png)

young explorer pack:
![screen shot 2018-01-23 at 16 04 38](https://user-images.githubusercontent.com/26549021/35286154-211513e8-0057-11e8-94bd-f9f1cf20d3b6.png)

these are all for Jan 2017-Jan2018
Entrances to these pages are 3-5 % except curiosities month which is 30% suggesting most people come to these pages from another page on the site rather than directly opening on them. But on average the pages get about 5 pageviews a day.

**Comment by jennpb** [comment]
Still do to:
`https://wellcomecollection.org/exhibitions/medicine-man` to `https://wellcomecollection.org/exhibitions/Weoe4SQAAKJwjcDC`

**Comment by pollecuttn** [comment]
@jennpb Does this also need to be done by 21 May? @gestchild is working on the Medicine Man temporary closure #2599

**Comment by jennpb** [comment]
Yup, it can be picked up with redirects. It's in the ToDo column.

**Comment by jamesgorrie** [comment]
Closing as these URLs have been redirected, and the migrated ones will be migrated with the Drupal migration piece of work.
