### ISSUE TITLE
Eventbrite ticket status information

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#2008]
## Type
- ✨ Feature

## Acceptance Criteria
- [ ] Promo should update with live status
- [x] Event page should update with live status

## Problem to be solved / User Story

In order to
see if tickets for a ticketed event are available without having to go to Eventbrite

As a
user

I need/want/expect 
to see ticket status information on wc.org

**Comment by jamesgorrie** [comment]
@pollecuttn this is already working on specific events.

Before implementing this - some user research would be nice, and a little bit of thinking around it.

Some questions:
* What if 1 date of a multi-date event is sold out - how do we allow users to know there are other available dates.
* What is the messaging for the differing states (sold out, coming soon, 3 left)

My main question would be, as this is not menial task to do, especially because of the way we unfold multi-date events into single date events on whats-on - do users benefit enough at knowing the ticket status at the listing stage?
