### ISSUE TITLE
Events UX: dealing with multi-date events with some interpretation (not all)

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2735]
Here's a case where we have one event across multiple dates, but one of the sessions has BSL and all the others don't.

## Who's the improvement for?
- content team
- people who can benefit from access enhancements

https://wellcomecollection.org/events/WwQzRyAAAF5rDkxL (BSL)
https://wellcomecollection.org/events/WwQzRyAAAF5rDkxL (BSL date included along with all others)

The problem is that
- the content team had to create a separate event for the BSL one in order to attach the interpretation
- the list of dates is actually really long - how do we deal with this, particularly on mobile
- relation to #2399

**Comment by jamesgorrie** [comment]
I still think, from a users perspective that having two events is a useful thing?

The event will be very different, and has different audiences in mind? Why overload the non-BSL event, and, in turn, potentially hide it from people whom it might interest? It feels like an event in it's own right.

We could also have different imaging for both, as they will be very different events - and we might want to look at putting the primary interpretation into the title for users, SEO, and sharing?

**Comment by jamesgorrie** [comment]
The link between the two could definitely benefit people, and that could be in the content?
Something like: "This event will be held in British Sign Language on the ___".
And: "There are also times without British Sign language...".

**Comment by Heesoomoon** [comment]
Update: We will leave it as is and monitor any future events with this type of edge cases to make any display logic changes.

**Comment by jamesgorrie** [comment]
Yea - the requirement is more about how do we make clear that some time slots might have different pieces of information attached. We will need more examples to work on this properly.

My comment above stands for primary interpretations, but I misunderstood, and this event actually only had an interpretation.

**Comment by jennpb** [comment]
Yes, it's only that the interpretation was added - not that the content or format of the event made it different.

I think we do have examples of where we attach different pieces of information to a time slot:
- event booking per event in a scheduled event
- event status (fully booked, and implied 'available')

The next time this arises I would like to deal with this, because we'll end up with a load of past events where we could have improved it but didn't because we were waiting for more examples.

**Comment by jamesgorrie** [comment]
@jennpb 💯 . The only big(ish) challenge is that we make sure we don't create two ways to do things.

e.g. We can add an interpretation to an event, and to a time. 
This creates complicated logic on the interface (and thus to users) and also to content producers.

So having a few examples would help us develop a better system and make the time spent on migrating to it worth while.

**Comment by jamesgorrie** [comment]
From @Heesoomoon https://github.com/wellcometrust/wellcomecollection.org/issues/2901#issuecomment-402118257

@jennpb Here's my latest thinking about the multi-date event with different interpretation.
Tell Us the Tooth and other stories
https://wellcomecollection.org/events/WwQzRyAAAF5rDkxL
Tell Us the Tooth and other stories with BSL https://wellcomecollection.org/events/WwQynCAAAF9rDklB

We should continue to have the content team to create a separate event.
- provides relevant event info: different booking info, contributor, customer service, etc.
- makes it easier to discover for visitors with access needs and not overwhelming them with irrelevant events.
- seems like an edge case (only 1 instance past 6 months) to revisit the display logic 

When we do the research with visitors with access needs, perhaps we can follow up on how they discover events and understand their expectation for this event use case. If you think otherwise, let me know. Happy to discuss more.
