### ISSUE TITLE
Events: multiple dates on event page

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2901]
When we have more that 1 time and date range on an event, the current `BasePage` `DateInfo` slot doesn't render in a way that is clear nor usable.

![somuchinfo](https://user-images.githubusercontent.com/31692/41862890-0f520fd0-789d-11e8-8d5d-cb22dee28172.png)

An approach we could take would be to:
- [ ] Define the purpose of the component
- [ ] Come up with how we might know it is achieving it's purpose
- [ ] Run it though some of the scenarios with live data

As mentioned in planning - having the content and programmes teams involved will give us good insight.

# Considerations
1. This has to work for ticketed and un-ticketed events, so the idea of "selecting" a time is not always that useful, as not all times will have a next action i.e. booking.

# Questions
1. How many times do we have multi-date events with booking?

**Comment by jamesgorrie** [comment]
# Questions

* How many times do we have multi-date events with booking?

**Comment by jamesgorrie** [comment]
# Ideas

## Primary / secondary date
* Have a primary date, that changes dependant on your entry point
  * If SEO / Social then the closest date to today
  * If What's on, the event that was selected
  
  Then have a "more dates" thing that shows more dates

**Comment by Heesoomoon** [comment]
@jennpb Here's my latest thinking about the multi-date event with different interpretation.
Tell Us the Tooth and other stories
https://wellcomecollection.org/events/WwQzRyAAAF5rDkxL
Tell Us the Tooth and other stories with BSL https://wellcomecollection.org/events/WwQynCAAAF9rDklB

We should continue to have the content team to create a separate event.
- provides relevant event info: different booking info, contributor, customer service, etc.
- makes it easier to discover for visitors with access needs and not overwhelming them with irrelevant events.
- seems like an edge case (only 1 instance past 6 months) to revisit the display logic 

When we do the research with visitors with access needs, perhaps we can follow up on how they discover events and understand their expectation for this event use case. If you think otherwise, let me know. Happy to discuss more.

**Comment by jennpb** [comment]
Sounds good :)

**Comment by jamesgorrie** [comment]
@Heesoomoon moved the comment here: https://github.com/wellcometrust/wellcomecollection.org/issues/2735#issuecomment-402196986

**Comment by jennpb** [comment]
See #2943 and #2944
