### ISSUE TITLE
Add 'full' status to events schedule on new events page

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#3105]
[Event_EB.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/2265832/Event_EB.pdf)
[Event_Email.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/2265833/Event_Email.pdf)
[Event_NoBooking.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/2265834/Event_NoBooking.pdf)

**Comment by davidpmccormick** [comment]
Adding booking status (e.g. 'fully booked') to each event in a multipart event using Eventbrite's API (instead of the widget) would involve writing some slightly convoluted logic at our end, as well as making several http requests (none of which could be cached, so would necessarily be slow).

Using Eventbrite's widget we can display this booking status with relative ease, the downsides being:
1. skinning the design would be limited
2. it doesn't display past events (although we _could_ display past events ourselves, i.e. outside of the widget)
3. there would be inconsistencies in design between the Eventbrite events and other events

An option would be to _not_ display booking status information (other than 'past') when it's an Eventbrite event (and possibly do the convoluted multiple Eventbrite API calls on the front end, if necessary).

It looks like the editorial team have been setting the `Fully booked` field (originally intended for use with email-to-book events) to 'yes' on Eventbrite events, even when this isn't the case. This disables the ticket booking button. We should find out what the use-case for this is and see if we can serve it better.

**Comment by jamesgorrie** [comment]
@davidpmccormick @Heesoomoon I thought the decision was to defer to the EB widget?
Yes?

**Comment by davidpmccormick** [comment]
Think so, yep (although we could show this inline for non-Eventbrite events?).

**Comment by jamesgorrie** [comment]
👍
