### ISSUE TITLE
A/B test: Discussion vs talk label on event cards

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3384]
# Date
TBD

# Page
`/whats-on`
`/events`
`/`

# Purpose / Hypothesis
To validate whether the user feedback that `discussion` can be somewhat daunting, and potentially misleading as to what we offer.

Discussion seems to imply that you will need to take part, where as what we offer is a discussion between panellists with a Q&A at the end, none of which requires mandatory participation.

Other organisations seem to use talk:
https://www.vam.ac.uk/whatson?type=talk
https://www.royalacademy.org.uk/exhibitions-and-events?group=talks_and_lectures

# Primary outcome
Primary: CTR on event cards will increase when labelled `talk` vs `discussion`
Secondary: Ticket booking on events labelled `talk` vs `discussion`

# Sample size / power
TBD

# Notes

**Comment by jennpb** [comment]
To me, [Library Insights](https://wellcomecollection.org/events/XdZreBEAAL8dJ73b) are good examples of Talks, whereas [Grief Gatherings](https://wellcomecollection.org/events/XbBeHxAAAEmAxmpW) is definitely a Discussion. 

I don’t think an AB test would be useful at this stage because the content of the events actually is quite nuanced and I don’t think it’s an either/or situation.
