### ISSUE TITLE
Events list: inconsistent ordering of event cards

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3407]
## Problem to be solved
- The event cards are displayed in random order. For example, 'Body image' on 8 Nov event is being displayed after 'Metals' on 21 Nov on 'What's on' and 'All events'
- Event cards are being displayed in the wrong months. For example, there are 3 November events in 'December'.

**Homepage**
![screen shot 2018-10-03 at 09 16 59](https://user-images.githubusercontent.com/29206031/46398510-385d7d80-c6ed-11e8-8226-32854046d5f4.png)

**What's on**
![screencapture-wellcomecollection-org-whats-on-2018-09-28-11_24_35](https://user-images.githubusercontent.com/29206031/46206039-ab947780-c31a-11e8-9299-32721055f190.png)

**All events**
![screencapture-wellcomecollection-org-events-2018-09-27-21_26_15](https://user-images.githubusercontent.com/29206031/46206032-a8998700-c31a-11e8-85e0-a81edf6f65db.png)

**Expected behaviour**
What's on: display events in chronological order starting with most recent upcoming event
All events: display events in chronological order starting with most recent upcoming event

**Comment by pollecuttn** [comment]
### TODO
/past/events
Only display here when all events are past

/whats-on and /events
Display by next upcoming event

Multi-month events
Leave as is: display in first month, not in second month; then display in second month when first month has passed

**Comment by Heesoomoon** [comment]
@jennpb Just to clarify, did we decide to remove the past events on /events and add a link to /events/past at the bottom of the list?
Also, we didn't get to discuss the ordering of the mixed list (This week on Homepage and Today/This weekend on What's on). Should we leave it as is or follow the same grouping/ordering we discussed for Exhibitions and Events?

**Comment by Heesoomoon** [comment]
https://wellcomecollection.org/events/past
The ordering in this past view has changed and I can't tell what order they are in anymore. Also, the event cards in the 1st and 2nd pages are identical.

**Comment by Heesoomoon** [comment]
To follow up on the conversation from @gestchild #3531 Events ordering, here are the usability reasons for removing Past events in /events
- Users often miss 'past' status and think all events in the list are available to attend
- It's likely people will miss the 'Past events' grouping in a long list
- Past events are only relevant when trying to find about specific event program i.e Packed lunch

Having said that, it wouldn't hurt to add 'Past events' link at the bottom of /events to allow for people looking for past events they've attended. (note: 265 clicks for Past events from What's on past 3 months.)

**Comment by gestchild** [comment]
# Exhibition and Events ordering on /exhibitions, /events and /whats-on

There is a disconnect between how we are able to query for a list of events or exhibitions from Prismic and how we want to display those lists to our users.

The following attempts to capture what is currently happening and to highlight some of the difficulties and potential problems.

## /exhibitions ordering

### Request from Prismic
- Each exhibition has a single date range with a start date and an end date.
- The request from Prismic retrieves all exhibitions in descending order based on their end date.
- Prismic doesn't deliver the results in one single response, but divides them across several pages.
- We retrieve 20 results per page (Prismic allows a maximum of 100 results per page).

### How we display

- For a page of results, we use the date range of each exhibition or it's 'isPermanent' property to place it in a time group (Permanent, Current, Upcoming and Past)
- We then display those groups in the following order: Current > Permanent > Upcoming > Past
- Within each group they still display in descending order as per the original request from Prismic.

### Potential problems
1. This works fine until any of the first 3 groups span more than one result page, because we can only do the grouping and re ordering for each page of results we receive. If, for example, the first page from Prismic contained exhibitions that belonged to the Permanent, Upcoming and Current groups and the second page contained exhibitions that belonged to the Current and Past groups, our reordering would mean the user would see Current, then Permanent, then Upcoming on page 1 (as desired), but would then see the next set of Current, followed by Past on page 2.

In reality, due to the limited number of Current and Upcoming exhibitions we have, this won't be a problem.

2. Having Past displayed in descending order makes sense, not sure it does for the Current and Upcoming groups?

## /events ordering

- For Current and Upcoming events, we want to display them in ascending order, i.e. starting closest to today and getting further into the future.
- For Past events we want to display them in descending order, i.e. starting closest to today and getting further into the past.
- We also want to display the events in the following groupings and order Current > Upcoming > Past

If we were to request the events from Prismic in descending order and then regroup them for display (as we do for exhibitions), we are far more likely to hit the pagination problem described above, as there are far more current and upcoming events.

- We therefore only request current and upcoming events from Prismic in ascending order and then can display them exactly as they arrive, without the need to Group and reorder.
- There were also [UX reasons for wanting to remove the past events](https://github.com/wellcometrust/wellcomecollection.org/issues/3572)

*An alternative solution would be to trust we never have more current and upcoming events, than the number that are shown on an individual results page (currently 100 - see below). We'd also then need to group the returned results and reorder the current and upcoming ones so that they displayed in ascending order.*

### Almost there
- Events can have multiple date ranges; rdering of events lists, returned from Prismic, is done based on the end date of the last date range that they have
- Ee only display the next upcoming date of the event, so they can appear to be out of order
- We therfore reorder the page based on the next display date of an event

### Potential problems
- The fact we reorder each results page based on the next display date of event, could lead to events appearing out of order
- This would happen if the last date in an events date range, puts it on a later page, than it's next upcoming date
- The likelyhood of this occuring has been mitigated by returning the maximum 100 results per page.

## /events/past
- An event can have multiple start and end dates
- When we request past events from Prismic, it uses the first end date it comes across to determine if the event is past
- As a result, events that have one or more past dates but still have upcoming dates are included in past dates
- We therefore have to filter these from the list before displaying

## /whats-on events ordering
- Event lists on the /whats-on page work in the same way as /events, but undergo an additional steps
- We group events into months
- Where events have multiple dates, they are duplicated for each month in which they occur (as long as that date has not already occured).

**Comment by jennpb** [comment]
:clap: Thank you for documenting the complexity @gestchild
