### ISSUE TITLE
Events: Booking integration for Schedule

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3421]
## Problems to solve
Displaying Eventbrite widget inline and making it work seem a bit tricky than anticipated. Also, it's not clear if allowing users to book multiple events from the schedule is the right workflow. 

Here are two models on the table.
![eventschedulebooking](https://user-images.githubusercontent.com/29206031/46341755-f969f200-c630-11e8-8da5-2d12e37289b5.png)

## Questions
- Should we allow user to book directly from the event schedule?
- Should we display Eventbrite widget inline in the Event schedule or Event page?

## Next steps
- [ ] Meet with the team to make decisions

**Comment by davidpmccormick** [comment]
_Document what’s up with EB widget and next steps for good UX_

## The story so far…
Adding booking status (e.g. 'fully booked') to each event in a multipart event using Eventbrite's API (instead of the widget) would involve writing convoluted logic at our end, as well as making several http requests (none of which could be cached, so would have performance implications).

There's also not an obvious way for us to associate any multipart event details from Eventbrite with the events that we display on the page (the Prismic versions and the Eventbrite versions aren't currently linked in any way). Implementing this would likely add extra overhead for the content editors.

All of which made it seem like the Eventbrite widget would be a good idea.

The Eventbrite widget has a bug that prevents its iframe from resizing (so the content wasn’t always visible). We couldn’t read the Eventbrite widget’s dimensions because of cross-domain restraints in JavaScript. We proxied the Eventbrite widget to a route on our domain so that we _could_ resize it. This loaded, but had other, more severe, cross-domain issues that removed the widget altogether as soon as a date was selected. So we reverted to a ‘Check for tickets’ link (styled as a button) for all Eventbrite events.

The benefit of the Eventbrite widget was that you could pre-select the date of the event you wanted to attend before being taken to an event page with that date selected at eventbrite.com. Now (with the link that we’ve fallen back to) you have to select dates on eventbrite.com before going to the individual event on eventbrite.com (and we only have the bare minimum of content on eventbrite.com, so the longer time spent there, the jankier the experience).

## Next steps…
_coming soon_
