### ISSUE TITLE
Article images not loading

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3432]
As of yesterday evening, images on articles aren't loading, first reported by @hthair 
https://wellcome.slack.com/archives/G5QLV74NM/p1538509612000100
Checked on mobile (iOS) and Desktop / Safari 

https://wellcomecollection.org/articles/W5D4eR4AACIArLL8
![screen shot 2018-10-03 at 07 14 41](https://user-images.githubusercontent.com/1446139/46393192-13144380-c6dc-11e8-9da2-faef35e668f6.png)

**Comment by jennpb** [comment]
So has this been fixed then @wellcometrust/experience-dev ?

**Comment by jamesgorrie** [comment]
@jennpb 

# Small retro

* Work was done on the new image gallery that affected the old templates negatively (see above bug). This work was done by @davidpmccormick 
* Deploying was held up due to some PR backup - this meant the above change wasn't deployed
* The hold up was fixed
* More work was done and deployed at the end of the day

I'm not going to put any analysis on this, and things that could have gone better as I feel that might be worth having everyone involved chatting about it.

@wellcometrust/experience-dev - fancy setting up a retro, or making notes to take to our official retro?

> So has this been fixed then @wellcometrust/experience-dev ?

We've rolled back and are serving the working version before the break - @davidpmccormick is on the forward fix.
