### ISSUE TITLE
Opening Times: closure dates and revised hours

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3439]
## Who it's for
Venue visitors and our content team

## Problem to be solved
The closure dates and revised hours are automatically populated based on the dates selected by the content team. This makes the information quite difficult to process and makes it unfriendly to the venue visitors. It would be ideal for the content team to add simpler and more friendly messaging.
Related to #2429 and #3062 

**Current Implementation** 
![screen shot 2018-10-03 at 08 51 56](https://user-images.githubusercontent.com/29206031/46405889-9e540000-c701-11e8-932c-8d0aaa84e2cc.png)

**Proposal**
Allow the content team to display simpler messaging and update as needed.
For example
**Closure dates for 2018**
**Christmas and New Years**
We will be closed 24, 25, 26 and 31 December and New Years day.
Library will be closed from 23 December to 1 January.
Galleries will be open with revised hours between 27-30 December.

## User Story/Job
**In order to** visit Wellcome Collection (galleries, library, and other facilities) during upcoming holiday/bank holiday
**As a** visitor
**I want** to know when Wellcome Collection is open.

## Acceptance Criteria
- [ ] The content team is able to add and update the messaging in Prismic for Closure dates and Revised hours section.
- [ ] The cotent team is able to preview the update in Prismic.
- [ ] Upcoming closure dates and revised hours are clearly listed.

**Comment by Heesoomoon** [comment]
#2429

**Comment by pollecuttn** [comment]
### To do - now
- [ ] Split table into 5 venues, each with regular and revised opening hours
- [ ] Tidy sentences of revised hours

### To do (future)

Identify what data we want to have
Identify what data we want to edit
Identify what data needs to go to Google etc for search engines

**Comment by Heesoomoon** [comment]
@pollecuttn 
I've added few additional recommendations we discussed during the meeting.

**Comment by Heesoomoon** [comment]
@jennpb Here's a quick sketch of how we can resolve both revised hours and closure dates for upcoming Christmas holiday. I think allowing the content team to put the right messaging would be a reasonable solution since revised hours occurs 5 times per year.

![ot_revised](https://user-images.githubusercontent.com/29206031/48911182-0a352800-ee6a-11e8-8b46-71aa3fdd7f16.png)

**Comment by jennpb** [comment]
@Heesoomoon @pollecuttn - An update:
- Jen is going to write the content blurbs as she wants them, including a summary at the top of the page. This will come to us next week.
- I'd then like to get this mocked up and put into an interactive prototype (Invision or similar) and see whether we can fit in some testing.

**Comment by hthair** [comment]
Research on two versions of opening times page carried out (DEC 18). Results shared with team and here in this doc: https://wellcomecloud.sharepoint.com/:w:/s/wcdigitalexperience/EaV3rdBoefxPj2JTaOiuv2MBywQL6BfUgTJs371jODhBxA?e=gdYpng

**Comment by Heesoomoon** [comment]
@hthair One thing we didn't consider in the testing is measuring cognitive load. When there is too much information to process, people tend to ignore reading and scan to seek for the information. I'm wondering the reason most people ignored the first paragraph in the current layout is that it's not written in a concise way. If Lyndsay is testing more on this, it might be worth following up on different methods to measure how much effort they spend to find the information.

Here's an article about why it's important to minimise the cognitive load especially for an information-heavy page like Opening times. 
https://www.nngroup.com/articles/minimize-cognitive-load/
"When the amount of information coming in exceeds our ability to handle it, our performance suffers. We may take longer to understand information, miss important details, or even get overwhelmed and abandon the task."

And here's how one company measured cognitive load using tapping test.
https://medium.com/@tsharon/measuring-cognitive-load-with-a-tapping-test-f07065854e46

**Comment by jennpb** [comment]
Here's what I emailed to VEAs: 
----
WHAT WE DID
We ran two rounds of testing in December:

Usability testing
The current opening times page was included as part of site testing with 5x ‘Researcher’ types. Lyndsay (our freelance user researcher) gave them a set of tasks to find out whether they could find the opening hours, and when they could visit various parts of WC. Full write up can be seen here.

Intercept testing
Hayley tested two versions of the opening times page: the current one, and a prototyped version that included opening times tables for Exhibitions/Library/Reading Room and Café/Kitchen/Shop. She talked to 8 people in total.

WHAT WE LEARNT
-	Both versions tested were ‘usable’ – People thought the information was very clear, and they were able to demonstrate that they could find the opening times, and understood where to view our modified times and closures. 
-	When testing the two versions against each other, there was no clear difference in usability between the two.
-	Some commented that the text size is a bit small (but not unreadable)
-	The long list of day-by-day closures was clear and easy to read for a majority of participants
-	Where we refer to ‘Venue’ and ‘Eat and Shop’, this caused some minor confusion: “Aren’t Eat and Shop also part of the venue?”
-	Google still used by some to find opening hours, but there is a recognition that what displays there isn’t always correct.

In summary: When people consult the website for opening times, they can find and comprehend them. But some visual design tweaks would help with overall look and feel of the Opening Times page and related components.


WHAT’S NEXT
Because there weren’t any real usability or findability issues identified through testing, we aren’t going to make any significant changes to the information or page design at this stage. However, we know that we need to attend to a few things before the next bank holiday in April:
-	Doing the work to see how we can improve opening hours on Google (for all WC spaces)
-	Improving the ‘tabbed table’ component that is both on the Opening Times page and in the footer
-	Finessing the page design: font size and information groupings, to improve legibility and scannability

As a short term, we’ll also be adding a text summary to the top of the page, and making it possible to add 2019 closures to the page so people can plan their visit well in advance (this is super important for library visitors who might be planning their summer research trips).

I’d also like to add Reading Room hours to the regular opening times component that you see in the footer. This would mean we’d organise our hours by:

Galleries (label TBC)
-	Exhibitions
-	Library
-	Reading Room
Eat and Shop
-	Café
-	Restaurant
-	Shop

**Comment by jennpb** [comment]
Short term tweaks to run through with JPB + @wellcometrust/experience-dev :

1. Add page summary 

Explore our opening hours across the different parts of our building. Keep in mind we're open late on Thursdays!

We'll have revised opening hours over the festive holidays. If you're planning to visit a long time in advance, check our planned closure dates for all of 2019.

(with anchor links)

2. Add future closure dates

3. Add Reading Room hours to table component

**Comment by jennpb** [comment]
`<p>Explore our opening hours across the different parts of our building. Keep in mind we're open late on Thursdays! We also have <a href="#revised">revised opening hours over the festive holidays</a>. </p>`

@gestchild This should use the featured text style (as with this page https://wellcomecollection.org/pages/Wuw2MSIAACtd3Ssg) but I don't see that documented anywhere in Cardigan.

**Comment by jennpb** [comment]
We need to revert back so that festive opening times aren't showing on the site anymore @wellcometrust/experience-devs

**Comment by gestchild** [comment]
@jennpb this should have happened automatically, which it looks to me like it has. Are you still seeing the festive times?

**Comment by jennpb** [comment]
Yes, I’m still seeing it on my desktop in Chrome (have F5’d the heck out of it)

**Comment by jennpb** [comment]
I’ve just deleted all cookies and it’s fine now.

Why so sticky though?

**Comment by jennpb** [comment]
Picking this back up again in preparation for the Easter weekend 2019.

Current hours: https://wellcomecloud-my.sharepoint.com/:w:/g/personal/j_phillips-bacher_wellcome_ac_uk/Ecx3vixTlV5DhYspvceh42EBr_zTp998UrpH8TdAnzMYLQ?e=8JH9te


## Problems to solve
- Simplify presentation of complex and variable hours on **Opening times page** and **in footer**
- Lack of in-site linky-ness
- Improve mobile view
- Give advance warning of closures
- Accommodate complex Christmas closures
- Provide general statement re: bank holiday pattern
- Inconsistent opening times presentation on related 'places' 

## Success measures / What makes this version better than the last?
- Tests well with dyslexic/dyspraxic users
- TBC

**Comment by jennpb** [comment]
@hthair Closing this issue now, but can you put it on the list for testing with neurodiverse visitors please?
