### ISSUE TITLE
Resolving clunky 'Guest edited' language

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3888]
# Problem to solve
We've got some clunky language where an article is part of a guest edited series. This is because we are titling the series 'Guest edited by (name).' Here are some examples of where it goes wrong:

Guest edited by LionHeart: https://wellcomecollection.org/series/W9B8oxIAAM1p1KEQ

**'Part of Guest edited by...'**
![partofguestedited](https://user-images.githubusercontent.com/1446139/50165977-ef759800-02dd-11e9-9c04-3eb641f52df3.png)

**Series Outro**
![seriesoutro](https://user-images.githubusercontent.com/1446139/50165987-f3091f00-02dd-11e9-9435-08c69c827f61.png)

Working with the content team, we should come up with some alternatives we can try, for example, giving the series a discrete title as we would a serial.

I'm sure there are loads of other ideas!

**Comment by jennpb** [comment]
@dannybirchall Do you have any thoughts on this? Ideas you want us to try?

**Comment by dannybirchall** [comment]
Thanks @jennpb!

It's our team's job to make the language work.

Looking at the list type:Story series,

https://wellcomecollection.prismic.io/documents/working~k=series&l=en-gb/

Lionheart is an early outlier, and most of the others work. We've done two guest edited weeks since then & just called them names that work in the navigational contexts. We should retrospectively fix Lionheart

We're aware that links to a Story series may take the form of:

'Part of [Story series]'
'Read more from [Story series]'
'Read more [Story series]'

So we can make sure the language we use doesn't clash with these.

Are there any others?

**Comment by jennpb** [comment]
No, I think that's it. If it's only Lionheart that poses the problem, we can close this issue. Hooray!
