### ISSUE TITLE
Beta Programme Messaging

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3959]
## Who it's for
Us, to get people using more than just 'Digital Images' on live site.
Our users, to set a clear expectation of the WIP state of Our Collections. 

## Problem to be solved
Have many people as possible to participate in Beta programme (#3958) so we can learn from their usage and issues

## Current Plan
Decided to open V2 API to all users to be able to collect necessary usage data. Therefore, we are moving away from 'Opt-in' model and replacing with Beta label and messaging across the 'Collections' section to set the right expectation.

## User Story/Job
As a keen and eager user of Wellcome Collection, I want to understand the latest status and see if it would be useful for my research.

## Acceptance Criteria
- [x] A user can tell the WIP status across the 'Collections' section
- [x] Find out what 'Our Collections' is about and the latest update (as part of [How we are improving search](https://wellcomecollection.org/works/progress))
- [ ] A user can feedback #3740 (report issues)
- [ ] A user can join user panel

## Things to consider
- Clear proposition and prominent 'Beta' label 
- Persistent through the Library Collections workflow
- Scale for different page templates e.g. landing, search result, works

## Questions
- Should we update 'Images' menu in the nav to something that describes all work types?
- How do we support existing users who are looking for images only?

## Status
- [x] @jennpb to review the model and provide direction
- [ ] Update #3740 based on the decision
- [ ] [Review the copy with Jen S.](https://www.notion.so/wellcometrust/3959-Beta-programme-opt-in-3883da8966e64f11bfca1839a3231d42) 

## Documents and demos
* [Technical document](https://docs.google.com/drawings/d/1OjD53NYisriMmjDnv1nlXbsGdodchkrLdYPOGwG2yt8/edit)
* [David's Demo](https://722o22oq90.sse.codesandbox.io/)

**Comment by jamesgorrie** [comment]
I wonder if there's also something about letting people know once something has been released that could be more contextual?

![screenshot 2019-01-15 at 18 06 06](https://user-images.githubusercontent.com/31692/51200067-5d6aaa80-18f0-11e9-871d-b4709659c98c.png)

**Comment by jamesgorrie** [comment]
To clarify a misunderstanding yesterday, I thought we would be having a way of letting users opt-in to beta features.

These are features that we knew weren't ready, or too large to A/B test, had a lot of unknowns, but at the same time user feedback would allow us to progress on them.

My new understanding on this, and please clarify on this, is that we were aiming for a more global approach where a person signs into beta, and then features go through the beta program.

My concerns with the later over the former were
* The beta programme might lead to release-bloat, where, because it's the programme, we leave it in there without a plan to get features out of beta until the very end. This was mitigated by @gestchild suggesting that we only every have 1 feature passing through beta at a time
* Feedback might be a bit harder action on as it would be based on more generic questioning (see #3740)
* It is a common pattern to use something like this on sites that are trying to move to V2 of the site where you are trying to usurp loads of functionality, and will move users over slowly. We did the for the old collection site, and this site, specifically the works section, is already the "`beta`" of wellcomelibrary.org, so it could be perceived as a beta in a beta.

The general approach of a global beta doesn't concern me too much, but the last point above I feel is something we should keep an eye on.

As much as we are building something new, and we are lucky as a library to do that, instead of splitting into another beta, I like to look at the work we have been doing as keeping the site in an almost permanent beta mode where we are able to test and iterate as the norm, not the exception, as that's the product I thought we were trying to build when splintering from the Drupal site.

**Comment by jamesgorrie** [comment]
Potential duplicate of #3959?

**Comment by kenoir** [comment]
My guess is that users will choose the experience they prefer and stay in that bucket (a significant amount of current users never choosing to switch to beta). Then comes switch over day and all those users who didn't want to try the new stuff get the new experience forced on them and get sad.

I don't really understand the approach. Pinging @Heesoomoon & @jennpb.

**Comment by jamesgorrie** [comment]
@kenoir There is still some ironing out to do - not sure that is 100% the direction that was suggested, but making sure if it's being explored, these issues are raised.

**Comment by kenoir** [comment]
Yup, to be clear i'd just like to understand the approach - recounting bad experiences i've had elsewhere isn't very positive. I'm sure you folk have thought about this already!

**Comment by Heesoomoon** [comment]
## User Insights
- Very few users tend to opt-in to the Beta programme
- Users don't differentiate between Search and Works but treat it as part of a journey of finding research materials 
- Users may start the journey from the Landing or Works and move around
- Our users are mostly new users and make infrequent visits (need to validate) 

## Beta Models
**Model 1 Allow users to opt-in to the Beta programme/section with ongoing feature updates** 
(note: we are going to explore this model and see if it meets the project goals)
Once users opt-in, they will see different features being updated continuously
e.g. Library Catalogue improvements which include updates to search and works 

Pros
- Simpler opt-in experience for the users
- More Beta participants

Cons
- Need to clarify which feature updates are grouped to a programme
- May have to run multiple Beta programme (Search enhancements and Aggregator)
- Concerns that a Beta programme "might lead to release-bloat" (as stated by James)
- Need to clarify which features will be A/B tested rather than being part of Beta

**Model 2 Run separate Beta for all new features**
We treat all new features as separate Beta and promote it contextually per component

Pros
- Allows the team to get targeted feedback
- Easier proposition?

Cons
- There will be multiple opt-in CTAs throughout the journey
- Potential user confusions which Beta they've opted in for
- Fewer participants 

![img_5044](https://user-images.githubusercontent.com/29206031/51254469-1b497380-1999-11e9-8df0-31d859b4e7ee.jpeg)

## Design Model 1
![img_5043](https://user-images.githubusercontent.com/29206031/51254507-2ef4da00-1999-11e9-9d3c-a90955a7ba7a.jpeg)

**Comment by jamesgorrie** [comment]
I think we need to come up with an implementation plan.

We can 100% start designing, building, and releasing this (to us behind a toggle) while we work out what are the first, simplest elements that would actually make the beta 👐 open for business 👐 .

The epic issue is being tracked here:
https://github.com/wellcometrust/wellcomecollection.org/issues/3958

**Comment by jennpb** [comment]
Some thoughts:

One angle that we may have missed is perhaps a more useful angle initially, is simply around stress-testing search in general (and then the new features/components feed into that). The first reason we'd want people to opt in to v2 search is to:

Get more people stress-testing collection search so we can:
- Get a better understanding of search behaviours across a larger set of data
- Track CTR from search results page (across this larger set of data)
- Monitor performance
- Collect qualitative feedback

Given the 2 models presented, Model 1 seems better than Model 2 if we want to achieve this. People would opt in to the new collections search, and whatever is new at that stage is what they'll see.

It's also a much simpler implementation and doesn't set this up as a 'beta programme' - which implies a commitment in some way. I also don't think we should bundle any other site features into this (e.g. editorial, venue or homepage work) as it makes the implementation more complex, piles too much analysis on our plates.

The messaging should pitch it as 'Try our new collections search' - and this can be lightly backed up with the `beta` tag

**Comment by jamesgorrie** [comment]
Flow diagram:
![beta workflow 1](https://user-images.githubusercontent.com/31692/51551139-bcd33800-1e65-11e9-83e9-7dc77ca58114.png)

**Comment by jamesgorrie** [comment]
Quite like AWS's version:
![potion](https://user-images.githubusercontent.com/31692/52409298-05792b00-2acd-11e9-8e02-371d9957be0f.png)

**Comment by Heesoomoon** [comment]
@jennpb I've updated the ticket info based on the decision of making the beta programme open to all users. Would you review and comment?

Here are some options @GarethOrmerod and I explored and our recommendations. 
**Display Options**
1. Global nav: difficult to message and hidden in mobile
2. Message bar below the global nav: discoverable but need to keep it short to avoid visual noise
3. Contextual to Search component: difficult to find consistent location since Search is work in progress and doesn't scale for all pages in Collections. 

After weighing in pros and cons, we decided it would be best to go with the **Option 2 Message bar**. 

**Beta & Feedback**
Then, we looked at whether to group Beta and Feedback or keep them separately.
**1. Combined** 
![beta_combined](https://user-images.githubusercontent.com/29206031/53555395-c1ac9b00-3b39-11e9-8271-a3de6f0ef6be.png)
- Single access point on top for Beta messaging/info and Feedback
- However, presents multiple choices to users and makes it visually noisy. (See the visual exploration below)
![beta_messaging_exploration](https://user-images.githubusercontent.com/29206031/53555645-3c75b600-3b3a-11e9-9f65-8fb0f47ced3c.png)

**2. Separate**
![beta_separate](https://user-images.githubusercontent.com/29206031/53555462-e0ab2d00-3b39-11e9-9939-a6566fbc404e.png)
- Display Beta messaging and link in the message bar and Feedback on the bottom corner (standard location)
- Doesn't tie the Feedback with Beta and may scale better for any additional feedback we may solicit in future.
![beta_messaging](https://user-images.githubusercontent.com/29206031/53556195-48ae4300-3b3b-11e9-9379-da13dcbc09b6.png)

We think keeping Beta and Feedback separate makes it a simpler experience and better solution.

**Comment by jamesgorrie** [comment]
Would we want to test both?
Not sure if "more feedback" is a good metric, but as we're getting none, it might be a good start?

**Comment by jennpb** [comment]
What remains to be done on this ticket:

- [ ] Agree format and design of `progress.md`
- [ ] Update release notes before go-live with latest issues
- [ ] Put a reminder in Slack to prompt us to add release notes if we have any
