### ISSUE TITLE
Browser issues with /works - IE and Edge on Windows

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4347]
Reported by Tom on Slack:
bug from Jenny Haynes: when looking at a works page with Edge on Windows (obviously) neither the book preview nor the view button are visible (the button appears momentarily before vanishing). I checked the same page on my MacBook Pro and it all worked OK so I assume it is a browser specific issue.

FWIW this was the works page: https://wellcomecollection.org/works/a22q99fr?query=optometry%20by%20the%20subjective but consistent bug across multiple pages

**Comment by jennpb** [comment]
Aha, I seem to have this problem (so you can use me for troubleshooting)

https://wellcomecollection.org/works/vyua3hdm
Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063
Windows PC

- Missing Download button
- Missing Preview

![image](https://user-images.githubusercontent.com/1446139/55492362-ffb44780-562e-11e9-80b4-632edc964115.png)

Checked against Chrome, which is all fine: 
![screenshot-wellcomecollection org-2019 04 03-16-42-21](https://user-images.githubusercontent.com/1446139/55492657-7c472600-562f-11e9-874f-e2557f29f61d.png)

**Comment by jennpb** [comment]
And on IE11 (Windows PC)

(also note logo!)

![image](https://user-images.githubusercontent.com/1446139/55492787-b6b0c300-562f-11e9-8004-61f63a9334ae.png)

**Comment by pollecuttn** [comment]
Logo issue noted at https://github.com/wellcometrust/wellcomecollection.org/issues/4365

**Comment by jennpb** [comment]
@gestchild We still have the issue in Edge with the Preview component
- Preview images not displaying, forces a CTA button to open full view
- Wobbly line cuts into text

![image](https://user-images.githubusercontent.com/1446139/58472934-53c73e00-813f-11e9-9cb9-9bbd73eef486.png)
https://wellcomecollection.org/works/mnygpdkg

**Comment by gestchild** [comment]
This only happens inside the building for computers on the network and I think is related to microsoft  site security zones.

It is happening because the fetch request for the manifest, e.g. https://wellcomelibrary.org/iiif/b11651222/manifest is failing. However, fetch requests to other APIs are fine.

This makes me think it is an issue similar to this: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18375494/

and which zone wellcomelibrary.org is deemed to be in.

"Due to the network isolation security feature in Microsoft Edge, this is expected to not work since we disallow an internet page to access an intranet resource."

Will talk to IT.

**Comment by pollecuttn** [comment]
Reboot of PC should make it pick up another policy change by Lloyd in Infra team. Tested on my Windows PC and various in the Library and the previews display for IE11 and Edge.
