### ISSUE TITLE
IE browser issue: promos not displaying correctly

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4366]
In IE 11 ~~cards~~ promos are not displaying correctly:
* there is too big a margin beneath the image
* information is 'pushed' off the bottom of the promo
* the yellow label is not on the bottom left of the image

![cards](https://user-images.githubusercontent.com/1446072/55493881-a13c9880-5631-11e9-8507-eb478882758a.PNG)

I'm seeing this on:
* https://wellcomecollection.org/
* https://wellcomecollection.org/whats-on
* https://wellcomecollection.org/exhibitions
* https://wellcomecollection.org/events

I'm using IE11 on Windows.

Promos look correct on Edge.

IE11 is on staff and Library PCs.

Please fix so that the:
- [ ] promos show all the relevant information
- [ ] the yellow label(s) are correctly positioned

**Comment by davidpmccormick** [comment]
I've started to look at this. It looks like whichever image from the `srcset` is used's _actual_ height is what is creating the extra space before the label and title.

Given promo images are always 16:9, we could use the intrinsic ratio ~hack~ technique to set the height of the containing element and hide the overflow. But that seems a little bit flakey.

Might be sensiblest to write classes specific to the promos (rather than using the root-scope classes) and have fallbacks for IE using `@supports` or similar.
