### ISSUE TITLE
Iterate on work preview with new designs

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#4379]
The work preview area should be able to accommodate 1–5 images at any aspect ratio. The number of images visible will be contingent on screen size/resolution as well as the aspect ratio of the images.

__Initial proposed dimension guidelines__ (from Zeplin):

![Screenshot 2019-04-11 at 17 37 30](https://user-images.githubusercontent.com/1394592/55974964-cd36ca00-5c80-11e9-8388-44ddff98b6e4.png)

Items should be centred if they would all fit within the viewport, otherwise they should be aligned flush to the left of the grid and flow off the right of the viewport (they'd be masked by the right of the viewport and wouldn't be scrollable).

__Examples with possible aspect ratio boxes__

![Screenshot 2019-04-11 at 17 36 44](https://user-images.githubusercontent.com/1394592/55975241-741b6600-5c81-11e9-9248-e738c2de6fe9.png)

__Examples with content__

![Screenshot 2019-04-11 at 17 37 06](https://user-images.githubusercontent.com/1394592/55975299-9614e880-5c81-11e9-889b-f3b57f8f28df.png)

__TODO__:
- [ ] Decide on (consistent) CTA messaging/location.

**Comment by jamesgorrie** [comment]
Looks great.

It'l be interesting to see if people expect the CTA to be on the right as that's where we sometimes put the cutoff?

**Comment by jennpb** [comment]
Before we start work on this, I'd like some baseline data for:
- Clickthroughs from Preview to Full View 
@hthair Can we get this data this week please?

**Comment by hthair** [comment]
Janeway release was 25th March, since then:
- 1406 times the book viewer has been launched (clicks to full view from preview)
- 20.4k pageviews in the book viewer 
- 113 PDF downloads. 
Although downloads may not be high, we can see that we're enabling a lot of content to be viewed online. This could be a really good thing as it shows that maybe people don't need to download in order to get the information they need and instead use the viewer.

**Comment by gestchild** [comment]
work completed in #4494
