### ISSUE TITLE
What's on month picker

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#4389]
An event that happens on multiple dates, which span more than one month, is not showing under each month on which it occurs .

**Comment by jennpb** [comment]
Relates to this, where we agreed to, but never actioned, the removal of the month picker: https://github.com/wellcometrust/wellcomecollection.org/issues/2939

I would say that we can do this now, but that would mean that the first event date (of a multi-date thing) needs to appear in chronological order, rather than last date in sequence.
