### ISSUE TITLE
Implement tracking on filters

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4694]
Implementation detail to be confirmed....

## Goal
- Get users to their own 'relevant' search results
- Users find more of what they're looking for, less of what they're not

## What we'll measure

People who use filters click results higher up in list 

- Median should be lower (getting thing you want higher up list)
- Change to CTR to works page

Using the filters

- Event tracking on filter component or URL

User satisfaction rating

- Did you find what you were looking for? Say Y more often than those who don't use filters

**Comment by pollecuttn** [comment]
@taceybadgerbrook Please check if the data team's tracking on filters will us what's what's need in this ticket and close if it does. If it doesn't, please get this tracking set up.

**Comment by jamesgorrie** [comment]
We have tracking on filters.
It's sent to the reporting cluster though, not GA.

Saying that we actually strip the queryParams from GA. @gestchild / @davidpmccormick do you know if we're doing that with the new params?

**Comment by gestchild** [comment]
The only param we currently strip is 'query'. Looks like GA will allow up to 5, we now have 6

**Comment by jamesgorrie** [comment]
Happy to discuss what we do with GA - we also need to talk about what we do with the 2 accounts, which feels like we need @taceybadgerbrook to lead on?

**Comment by taceybadgerbrook** [comment]
I'm digging into the 2 original accounts Collection (55614-6) and Library (5739409-1) and the new account that combines them (55614-24) to ensure that if we drop the first 2 that the 3rd will be ok.  If you need to tag them right away, can you tag all of them?

**Comment by pollecuttn** [comment]
SearchForm event in GA, and the query label says which filters have been used.

**Comment by jennpb** [comment]
User satisfaction rating - move to new issue

**Comment by pollecuttn** [comment]
@taceybadgerbrook to look into the use of the filters in the reporting cluster

**Comment by taceybadgerbrook** [comment]
I can see date filter usage from 19/11/19 and all of the fields I'll need to analyse this except for the search relevance rating.  There's a field called, "score" but this has 0's in it even when toggle shows  relevanceRating:true.

**Comment by pollecuttn** [comment]
@taceybadgerbrook This was moved to 'done' last week so can it be closed now?

**Comment by jennpb** [comment]
Are we tracking use of the filters components now @taceybadgerbrook @wellcometrust/weco-experience-devs ?

**Comment by taceybadgerbrook** [comment]
index:search relevance explicit is tracking relevance ranker (term:relevanceRating.) Index:search relevance implicit is tracking date filter usage (terms:query.production.dates.from,  query.production.dates.to)

**Comment by jennpb** [comment]
This isn't about the explicit relevance ranking, but about the filter UI: dates, formats, and any future filters that we add
![image](https://user-images.githubusercontent.com/1446139/72723874-b01d1900-3b79-11ea-8970-731ff30a72e5.png)

Is the decision then to track UI usage in Kibana? Or event tracking in GA?

**Comment by jamesgorrie** [comment]
@jennpb we have two cases for collecting data in elastic (and analysing through Kibana).

Data collected is specifically to help us with relevancy ([see what we track here](https://docs.wellcomecollection.org/catalogue/search_relevance#explicit-vs-implicit-measurement)). We thus just track what a person has searched, what we've returned, and what they have selected.

We haven't really been inquisitive as to what part of the interface they used.

Saying this, there is a bit of work we've been talking about about adding a `source` to events, e.g. `SearchForm`, `SubjectTag`, `GenreTag`, `LandingPageTag` that might help with this.

We're intentionally specific about the data we collect as the analysis done on it is also very specific, and we don't want to be tracking things we don't run analysis on. 

For this I imagine the conversation we had around a more generic logging system would yield more fruitful results, rather than hijacking the relevancy system.

**Comment by jennpb** [comment]
@wellcometrust/weco-experience-devs @jamesgorrie @taceybadgerbrook Let's have a discussion about what elements we should be tracking and why. As you know, we used to track use of UI components with GA event tracking. So if we're deciding *not* to use event tracking for some parts of the interface, we should be explicit about it and keep a record of when/why to use events and when/why to use the data from the relevancy system.

I don't need the detail of what, I just need to understand the decisions behind it.

**Comment by taceybadgerbrook** [comment]
This ticket was created before any search filters had been deployed.  In order to be able to evaluate the success of filters, it was agreed that use of the filters would be tracked.  Previously, events had been tracked in GA.  It's not so much about which tool is used but the fact that usage must be tracked and reasons for/against the tracking methods should be recorded (I'm happy to do this bit!) and reviewed regularly so that the use case is always valid.

So this ticket is now about answering the following questions:-

1. How are the filters we've deployed so far being tracked?

We currently have two filters:  Date and Format.  The Date filter usage is being tracked in Kibana.  

The Format filter is not being tracked in either Kibana or GA.  Although currently, the Formats offered are limited to image/non-image and historic GA events such as IIIfImagePreview can be repurposed to evaluate usage, this will not be able to monitor filter usage when video and sound formats become options.  

**2. Was there a discussion about how these filters would be tracked?**
3. What reasons were put forward for tracking them in this way?

Date filter:
**a) What was the reasoning behind tracking this in Kibana?
b) Why not use GA when historically this has been the way features have been tracked?
c) Is it because relevancy is tied to filter usage?**

Formats filter:
**d) Why is this filter not being tracked in GA?  
e) Why is this filter not being tracked in Kibana same as the Date filter?**

Future considerations:
**4. What should we do to ensure tracking of filters takes place in the future?
5. How can we ensure future tracking is consistent/thought through?
6. What mechanism can we put in place to ensure the tracking remains effective/relevant?**

**Comment by jennpb** [comment]
> 4. What should we do to ensure tracking of filters takes place in the future?

Rather than tracking filters specifically, I think the bigger discussion is around tracking of _any component use_ generally. 

As we're tracking use of data filters and format filters with the URL via Kibana, this ensures that we can look at filter use in general, and this should be proactively monitored to see whether users are using it as part of a search journey (and whether we might have questions about its use that can be picked up in qualitative research).

> 5. How can we ensure future tracking is consistent/thought through?

I'd like to have a conversation about Why Measure Use of UI Components At All, and in the abstract what we might plan to measure in the future (e.g. key stages of a user journey; only track what's important as Goals instead of Events; or track all actionable js events. @pollecuttn That feels like a good topic for a team conversation. It'd be good to set ourselves some guidelines.

> 6. What mechanism can we put in place to ensure the tracking remains effective/relevant?

This is dependent on what we decide in a team convo.

**Comment by jamesgorrie** [comment]
> I'd like to have a conversation about Why Measure Use of UI Components At All

This is a great question!
