### ISSUE TITLE
Design QA: checkbox states

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4983]
When you open a filter, the first item in the list is black as if selected. All other items appear to be greyed out (they're not, but the grey makes it look as if that were the case).

I would expect that when nothing has been selected, all values are same font colour/weight. It's probably best that these are black or charcoal, not grey.

@GarethOrmerod @davidpmccormick @gestchild What do you suggest?
![image](https://user-images.githubusercontent.com/1446139/72081251-0d050d80-32f6-11ea-9e9d-509f9620dda0.png)

**Comment by davidpmccormick** [comment]
Yes, this isn't ideal – I was looking for a way to make selected, checked, and focused distinguishable, but agree that they look more disabled when greyed-out. Maybe use a bit of the old look-at-what-airbnb-do-and-do-that technique might help in this instance

**Comment by jamesgorrie** [comment]
Don't checkboxes normally leave the label unchanged, and highlight and check the box to indicate state? I think that's standard browser and AirBNB design.

<img width="210" alt="Screenshot 2020-01-09 at 17 20 31" src="https://user-images.githubusercontent.com/31692/72089860-c36fef00-3304-11ea-8223-3a450446a51e.png">

Otherwise you start creating tag like selectors, which normally wouldn't have the checkbox as the whole component indicates state. [Something more like chips](https://material.angular.io/components/chips/overview).

Just a thought.

As another point, should we have the cursor set to pointer on the label?

**Comment by davidpmccormick** [comment]
Part of the reason for this looking strange is that when you open the filters, we move focus to the first checkbox (it appears selected, because it is). But the un-focused/un-selected checkbox labels being greyed out confuses things further, I think.

Is this better?

![image](https://user-images.githubusercontent.com/1394592/72091997-5c086e00-3309-11ea-9c43-c384b05bee5d.png)

> As another point, should we have the cursor set to pointer on the label?

Couldn't hurt, could it.

**Comment by davidpmccormick** [comment]
Regarding keyboard-nav-only focus states, this relatively straightforward approach Facebook (apparently) use makes sense to me. It involves adding/remove a class to the document el based on whether or not a `click` or `keydown` event fires.

https://codepen.io/davidpmccormick/pen/Jjovddj
