### ISSUE TITLE
Changes to V1 site for release

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#499]
Changes to be made externally for release:
- [x] Changing the URL for "Explore" on `https://wellcomecollection.org`'s navigation to `https://next.wellcomecollection.org`.
- [x] Add banner to `https://wellcomecollection.org` (copy to TBD).
- [x] Add promotion module to homepage of `https://wellcomecollection.org` (Copy / Image TBD)

So we need:
- [x] Copy for banner
- [x] Copy / image for promo

**Comment by jamesgorrie** [comment]
In line with [this strategy](https://github.com/wellcometrust/wellcomecollection.org/wiki/V1-=--V2-URL-migration-plan).

**Comment by jennpb** [comment]
@jamesgorrie 

- I don't think we need a banner on WC, so I've ticked that one off. 

- @Norvard gave @RussellDornan some promo images that can be used on WC.org homepage, so that one's sorted too. Whenever @RussellDornan has some free space on the homepage we can promo it there (or individual articles / series as he sees fit!)

So that leaves changing the link to the blog in the WC footer #589 

Woo!
