### ISSUE TITLE
Promos: Linking to article/format index page and signposting series/story title

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#514]
Could the hit area be only the image and title. Currently it seems to be the entire module area. This way when the user hovers outside image and title, the zooming releases

**Comment by jamesgorrie** [comment]
It also stops copy / paste.

**Comment by jamesgorrie** [comment]
Let's have a chat about this @Norvard @gestchild @jennpb as having the article link on image, then content type link, then article link on title feels like a clunky user experience.

**Comment by jennpb** [comment]
I agree it's clunky.

On early designs (the printed one on the whiteboard), the content type above the article is not a link to the index page - there's a link to see more at the bottom of the component. If we do it that way, the image and title will be linked, but not the content type.

**Comment by Norvard** [comment]
The only reason we discussed making the format/content type linkable was because we did not have a sub-nav on the page. So the only way for people to have access to index pages is through these links. The same goes for video, digital stories etc.

We do have a plan in place to build a format navigation component thats attached to the footer on Explore which links you to all format index pages.

Its a pretty common practise within editorial sites to have format indicators link to index pages. Same model goes for other meta data such as author.

**Comment by Norvard** [comment]
While we do have some components which have explicit links such as "see all articles", we should adopt a model which works across the experience. If we do not have a particular component with the above mentioned link, how does a user get to index pages for articles, video, audio etc?

**Comment by jennpb** [comment]
See #880
